feat: validate major version being inferior to Java 18
gatling/gatling-scanner pull request #3
Opened 2022-04-12 13:46 UTC by tpetillot

**Motivation:**
We do not support higher version of java than 8

**Modification:**
Throw 'UnsupportedJavaMajorVersionException' when a candidate have an
invalid java major version.

**Ref:** CLOUD-1424

2022-04-12 13:59 UTC, slandelle requested changes
Overly complicated. There's one thing Java Exceptions are good at (and streams are bad at): interrupts.
You could just throw your UnsupportedJavaMajorVersionException after loading the ClassNode, without carrying the extra 4 bytes luggage on each AsmClass instance.

2022-04-12 14:13 UTC, tpetillot commented
@slandelle this does not allow to report invalid classes to the user. (which may be useful, when coming from a library for example)

2022-04-13 09:19 UTC, slandelle requested changes

2022-04-13 09:19 UTC, slandelle commented on src/main/java/io/gatling/scanner/JavaMajorVersion.java
> +  JAVA_18(62, "Java 18");
We don't care about Java 18. We care about Java 17 which is our highest supported version.
You can compute the Java major version from the bytecode version: bytecode version - 44.

2022-04-13 09:19 UTC, slandelle requested changes

2022-04-13 09:19 UTC, slandelle commented on src/main/java/io/gatling/scanner/JavaMajorVersion.java
> +        >= JavaMajorVersion.JAVA_18.majorVersion) {
Change it to > Java17

2022-04-13 09:22 UTC, slandelle requested changes

2022-04-13 09:22 UTC, slandelle commented on src/main/java/io/gatling/scanner/JavaMajorVersion.java
> +      throw new UnsupportedJavaMajorVersionException(classNode, JavaMajorVersion.JAVA_18);
We want to pass our max supported Java version and the actual Java version used. We don't want to break this when Java 19 is out.

2022-04-13 11:34 UTC, Isammoc commented on src/main/java/io/gatling/scanner/AsmClass.java
>    public final String parentName;
In commit message:
We do support java version above 8... up to 17 (included)

2022-04-13 11:34 UTC, Isammoc commented on src/main/java/io/gatling/scanner/AsmClass.java
> +    JavaMajorVersion.checkNode(classNode, JavaMajorVersion.JAVA_17);
**design**
I'm concerned about having hard coded value that will change over time.
When we will release the gatling injector supporting Java 18 (or 22 for that matter) we should not have to change plugins for that!

Therefore, the scanner should not throw anything, I guess, but return the highest value found in the jar.
The user (of this library) will set its own limit.

At least, the acceptable value(s) should be an argument

2022-04-13 11:34 UTC, Isammoc commented on src/main/java/io/gatling/scanner/JavaMajorVersion.java
> +  JavaMajorVersion(int majorVersion, String noun) {
default visibility should be avoided when possible!
```suggestion
  private JavaMajorVersion(int majorVersion, String noun) {
```

2022-04-13 14:53 UTC, slandelle requested changes

2022-04-13 14:53 UTC, slandelle commented on src/main/java/io/gatling/scanner/AsmClass.java
> +    JavaMajorVersion.checkNode(classNode, JavaMajorVersion.JAVA_17);
It was my proposal to have this centralized in the scanner to not duplicate the error message.
But I've come to realize that the error messages must be specific to the caller. Typically, we want to provide a hint on how to configure the build tool to have `--release` set.

I like your proposal of having the scanner report the highest Java version used in the package and let the caller deal with it.

2022-04-13 14:53 UTC, slandelle commented on src/main/java/io/gatling/scanner/AsmClass.java
> +    JavaMajorVersion.checkNode(classNode, JavaMajorVersion.JAVA_17);
Now, if we don't want to have to update the clients when changing the max supported Java version, it means we need an API to advertise it.

2022-04-14 16:03 UTC, closed without merging