feat: return highest java version class along discovered simulation classes, closes MISC-369
gatling/gatling-scanner pull request #4
Opened 2022-04-14 16:02 UTC by tpetillot

**Motivation:**
We need to check if we support the highest version present in a package.

**Modification:**
Extract highest java version class while extracting candidates.

2022-04-14 16:02 UTC, tpetillot commented on src/main/java/io/gatling/scanner/AsmSimulationScanner.java
> +    final AtomicReference<AsmClass> highestClass = new AtomicReference<>();
Java 😭

2022-04-14 16:35 UTC, slandelle requested changes

2022-04-14 16:35 UTC, slandelle commented on src/main/java/io/gatling/scanner/AsmSimulationScanner.java
> +    final AtomicReference<AsmClass> highestClass = new AtomicReference<>();
Why do you need concurrent safety here?!

2022-04-15 07:40 UTC, tpetillot commented on src/main/java/io/gatling/scanner/AsmSimulationScanner.java
> +    final AtomicReference<AsmClass> highestClass = new AtomicReference<>();
Otherwise I got an error that in lambda, expression should be final or effectively final... Let me know if there's any alternative solution 🙏

2022-04-15 07:51 UTC, slandelle commented on src/main/java/io/gatling/scanner/AsmSimulationScanner.java
> +    final AtomicReference<AsmClass> highestClass = new AtomicReference<>();
possibilities:

1. don't use Stream API
2. live with it

Ideally, we should measure the overhead. Could you please try the 2 options with a huge package, eg one shipping Spring?

2022-04-15 08:30 UTC, tpetillot commented on src/main/java/io/gatling/scanner/AsmSimulationScanner.java
> +    final AtomicReference<AsmClass> highestClass = new AtomicReference<>();
Bench: 1002 entries that are classes. (4.5MB), 300 iterations.

Without stream API: 21.5 seconds
Current implementation: 21.5 seconds

2022-04-15 08:33 UTC, tpetillot commented on src/main/java/io/gatling/scanner/AsmSimulationScanner.java
> +    final AtomicReference<AsmClass> highestClass = new AtomicReference<>();
So no noticeable differences, but I think it's more natural to go without the stream API (avoid confusion coming from the atomic reference)

2022-04-15 08:40 UTC, slandelle commented on src/main/java/io/gatling/scanner/AsmSimulationScanner.java
> +    final AtomicReference<AsmClass> highestClass = new AtomicReference<>();
> 21.5 seconds?????????

2022-04-15 08:41 UTC, slandelle commented on src/main/java/io/gatling/scanner/AsmSimulationScanner.java
> +    final AtomicReference<AsmClass> highestClass = new AtomicReference<>();
Ah oui, 300 itérations :)

2022-04-15 08:41 UTC, slandelle commented on src/main/java/io/gatling/scanner/AsmSimulationScanner.java
> +    final AtomicReference<AsmClass> highestClass = new AtomicReference<>();
OK, live with it it is.

2022-04-15 09:34 UTC, tpetillot commented on src/main/java/io/gatling/scanner/AsmSimulationScanner.java
> +    AsmClass highestClass = null;
I'm a bit hesitant on this null value... A Jar shouldn't have 0 classes, but if it does...

2022-04-15 09:47 UTC, Isammoc commented on src/main/java/io/gatling/scanner/AsmSimulationScanner.java
> +    AsmClass highestClass = null;
You'll have to check it!

Samples:
* `myproject-2.0.0-sources.jar`: only sources... no classes
* `mytestrepo-4.2.1.jar`: a project with only test source, so the default configuration will produce an empty jar, (note: `mytestrepo-4.2.1-test.jar` may have the wanted classes and by default will depend on the former jar)

2022-04-15 10:07 UTC, slandelle requested changes

2022-04-15 10:07 UTC, slandelle commented on src/main/java/io/gatling/scanner/AsmClass.java
> +  public final int bytecodeMajorVersion;
rename: javaVersion. There's no longer any notion of major and minor in Java versioning scheme.

2022-04-15 10:07 UTC, slandelle commented on src/main/java/io/gatling/scanner/AsmSimulationScanner.java
> +      if (maybeCandidate.isPresent()) {
What's the point of using Optional if it's for using it this way?

2022-04-15 10:43 UTC, slandelle approved these changes

2022-04-15 12:29 UTC, bastien-gatling approved these changes

2022-04-15 12:33 UTC, merged